file_format: "1"
id: charybdis_nano
name: Charybdis Nano
type: shield
url: https://github.com/Bastardkb/Charybdis/
requires:
  - pro_micro
features:
  - keys
  - trackball
siblings:
  - charybdis_nano_left
  - charybdis_nano_right
